### ISSUE TITLE
Entity unavailble after restart of HomeAssistant

### ISSUE THREAD

**Issue by davebartles** [briis/weatherbit#1]
If I restart the HomeAssistant server, the entity remains but says it is unavailable or disabled and no data is available.

If I remove the integration and add it back with the API key it works again until restart.

Thanks

David

**Comment by briis** [comment]
Thanks for reporting this. Can you tell me what version of HA and Weatherbit you are running?
I will look in to this ASAP, as I am planning some changes at the same time.

**Comment by davebartles** [comment]
Yep HA version is 0.110.1 but I see 0.110.2 is now out as well but havent updated yet. Weatherbit is installed via HACS and showing 0.5 if I am reading it correctly.

Thanks

David

**Comment by briis** [comment]
Thanks. I will do a major update one of the next days, that might break the current installation, but then hopefully will give a solid implementation.

**Comment by davebartles** [comment]
Great sounds good. Thanks for the awesome integration :)

**Comment by briis** [comment]
I was told that there could be some issues with Integrations missing entities in 0.110.1 but it should be fixed in 0.110.2. When you have upgraded to 0.110.2 could you please try to see if the Entity will stay available.

**BTW** I cannot reproduce the error, on any version of HA

**Comment by davebartles** [comment]
Ive updated to HA 0.110.2 and version 0.6 of the integration. Ive removed the integration after updating and rebooted a couple of times and so far so good. Will keep an eye on it, as still adding stuff so will likely need to reboot again. Thanks again for your help

**Comment by briis** [comment]
Good to hear. Close this issue once you feel secure that the problem is fixed.

**Comment by davebartles** [comment]
Looks fine again now. Thanks very much again
