### ISSUE TITLE
language and unit support

### ISSUE THREAD

**Issue by andilge** [briis/weatherbit#13]
Please add multi language support provided by weatherbit.io current api. Here the array:

_lang=[language](optional)_
en - [DEFAULT] English
ar - Arabic
az - Azerbaijani
be - Belarusian
bg - Bulgarian
bs - Bosnian
ca - Catalan
cz - Czech
da - Danish
de - German
fi - Finnish
fr - French
el - Greek
es - Spanish
et - Estonian
hr - Croation
hu - Hungarian
id - Indonesian
it - Italian
is - Icelandic
iw - Hebrew
kw - Cornish
lt - Lithuanian
nb - Norwegian Bokmål
nl - Dutch
pl - Polish
pt - Portuguese
ro - Romanian
ru - Russian
sk - Slovak
sl - Slovenian
sr - Serbian
sv - Swedish
tr - Turkish
uk - Ukrainian
zh - Chinese (Simplified)
zh-tw - Chinese (Traditional) 

Same for units, here the array
_units=[units](optional)_
M - [DEFAULT] Metric (Celcius, m/s, mm)
S - Scientific (Kelvin, m/s, mm)
I - Fahrenheit (F, mph, in)

many thx + all the best

**Comment by briis** [comment]
Hi @andilge 
I will implement the Language Option, but not the Units. Units are already supported in the way that if you select Metric or Imperial Units in Home Assistant that is the way you will see data.
I don't see a use case for the Scientific units in Home Assistant.

**Comment by briis** [comment]
Release 0.21 is now out, and that has support for setting the Forecast Language. As stated above, adding Unit Support is already done, as it follows the units set in Home Assistant.

**Comment by andilge** [comment]
Many thanks Bjarne, you're the man.
[image: image.png]

All the best, Andi


Am Sa., 13. Juni 2020 um 09:00 Uhr schrieb Bjarne Riis <
notifications@github.com>:
