### ISSUE TITLE
please add sensor for Ozone

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#14]
as discussed on https://community.home-assistant.io/t/weatherbit-io-current-weather-and-forecast-data/200224/118?u=mariusthvdb

thanks!

**Comment by briis** [comment]
Hi
Just looked at the API, and ozone is actually not part of the current data api, and the sensors are based on that api. I can add it as an attribute to the forecast_day_x sensors, but then you might as well extract it from the weather entity.

**Comment by Mariusthvdb** [comment]
adding it to the forecast sensors would only be useful if you have the data available for all forecasts?

What does generate it now, so it is displayed on the weather forecast card? Is there another data flow?

**Comment by briis** [comment]
It is part of the 16 Day Forecast API. I could pull Ozone from Day 1 of the Forecast, but it would be a static value for the whole day - and the same you see on the Weather Card.
And as it is part of the Forecast API, the value is available for all days, but would still require you to make a Template sensor

**Comment by briis** [comment]
As stated this can unfortunately not be done, as the data is not in the API, so I will close this. Please re-open if you have other ideas.
