### ISSUE TITLE
consider breaking out forecast sensors

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#16]
in the integration itself, so users dont ned to create template sensors for all forecast days.

as discussed per: https://community.home-assistant.io/t/weatherbit-io-current-weather-and-forecast-data/200224/124?u=mariusthvdb

thinking of replacing dark_sky which does just that, and allows to have this in frontend:

<img width="346" alt="Schermafbeelding 2020-06-16 om 15 01 04" src="https://user-images.githubusercontent.com/33354141/84827893-6f8cd300-b025-11ea-826b-fc959f97d48f.png">

and detail:

<img width="352" alt="Schermafbeelding 2020-06-16 om 15 01 13" src="https://user-images.githubusercontent.com/33354141/84827910-774c7780-b025-11ea-80b3-8bf5cb15e5cf.png">

**Comment by briis** [comment]
Hi Marius,
After thinking about this for a while, I decided not to do this. I believe all the data people need is already present, and getting the data is possible, without me trying to simulate what DarkSky was doing before. Sorry about this, if it is really important to you.
