### ISSUE TITLE
add solar sensor with attributes

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#19]
on the api.weatherbit.io a set of solar data is displayed, we mentioned these in the community.

second thought would lead me to the question to please add these as a solar sensor, with attributes for
solar_rad":244.241
"h_angle":-20,
"sunset":"20:05",
"dni":898.26,
"sunrise":"03:17",
"ghi":887.52,
"dhi":118.1
"elev_angle":55.11

since this is the first time I see many of these in a weather integration, I feel these could be valuable for people using solar energy, and like to use these in a history graph combined with their solar production

sunrise and sunset might not be very relevant in that aspect, but since they're here, why not just add them ;-) always nice to have a back up if any of the other sun sensors act up..

**Comment by briis** [comment]
Hi 
The Solar radiation and UV sensors are already done. So are you suggesting that we add Attributes with the above to one of those sensors?

Also Sunset and Sunrise only deliver the Time Piece so f.ex 21:54 for Sunrise. It ease to add that, but if you want a full DateTime object it gets a little more complicated.

**Comment by Mariusthvdb** [comment]
> Hi
> The Solar radiation and UV sensors are already done. So are you suggesting that we add Attributes with the above to one of those sensors?
> 

yeah, that would be an option, or, create a new sensor with these 2 s attributes also

there some obvious logical combining:

- sunrise, sunset

- solar_rad, uv

- h_angle, elev_angle
  dni, ghi, dhi

though not 1 specific 'main' value, to which the other attributes could be added to, unless you would use the ob_time maybe, to which all but the sunrise and sunset could be added. 

Id suggest 2 separate sensors for those in that case, to prevent the scenario you describe, if having to create a full datetime object..

that would be overdoing things








> Also Sunset and Sunrise only deliver the Time Piece so f.ex 21:54 for Sunrise. It ease to add that, but if you want a full DateTime object it gets a little more complicated.

**Comment by briis** [comment]
Ok, thanks for the feedback. To not implement a Breaking change by removing sensors, I will add all this data as extra Attributes under the Solar Radiation sensor, as this is the place where I find it most logical to add them.

**Comment by Mariusthvdb** [comment]
That would be wonderful and much appreciated!

**Comment by briis** [comment]
Implemented in Release #V0.25
