### ISSUE TITLE
Reports Clear, Night even during the day

### ISSUE THREAD

**Issue by austwhite** [briis/weatherbit#2]
There was recently a change to introduce Clear, Night as a weather summary.
Now Clear, Night is reported, even when the sun is above the horizon. 
If the weather remains clear, it seems to stay at Clear, Night.

Home Assistant Core version 0.110.2
WeatherBit Version : v0.5

**Comment by briis** [comment]
Thanks for the report. I haven't had a clear night here for a long time, so it has been hard to test.
There will be some delay to changing as the component is only updated every 30 min. but it should revert back to a sun symbol. When this happen, can you check the `is_night` attribute on the Integration and let me know if this shows False or True.

**Comment by austwhite** [comment]
@briis 
Its 14:35 here now and the sun rose several hours ago.
From states page:
cloudiness: 0
is_night: true
precipitation: 0
wind_gust: 7
uv_index: 4.2

**Comment by briis** [comment]
OK, thanks. I'll look at the code it see where it goes wrong.

**Comment by austwhite** [comment]
Thanks.  It's taken a while to pick this up because I haven't had a clear night for a little while either 🙂

**Comment by briis** [comment]
Btw, how accurate is the data at your location? For Denmark, where I live, the current data is not that good, but forecast seems OK.

**Comment by austwhite** [comment]
I find it more accurate than OpenWeatherMap for me, but it can be hit and miss.  
The forecasting is usually accurate enough for my purpose, but not quite up to DarkSky

**Comment by briis** [comment]
I am close to a solution. For me to test, could you supply your timezone and when sunrise and sunset occurs?

**Comment by austwhite** [comment]
I am in timezone GMT+10.
Sunrise is about 7:23 and sunset is about 17:13

**Comment by briis** [comment]
Thx.

**Comment by briis** [comment]
I pushed a new release, that hopefully takes care of this. Please let me know if the `is_night` attribute is close to accurate taking in to account that the update only occurs every 30 min.

**Comment by austwhite** [comment]
It's currently night here, so it will be some time before I see if it changes.
I'll update and let you know in the morning

**Comment by austwhite** [comment]
Sorry for the delay responding.
The "is_night" attribute seems to have updated correctly today.
```
aqi: 27
cloudiness: 31
is_night: false
precipitation: 0
wind_gust: 8.5
uv_index: 3.3
```
Ill keep an eye on it.  Unfortunately we are back to cloudy weather so I can't test the clear again for now.

**Comment by briis** [comment]
Thanks. Just follow the is_night attribute, as this is what determines if the icon changes or not and that is not dependent upon the weather, just your position.

**Comment by austwhite** [comment]
It looks like whatever update you made has fixed it.  
If it is okay, can we keep this open for a day or two just to monitor, then I will close.

**Comment by austwhite** [comment]
This looks to be working well now.
Happy to close.
Thanks for all your help :)
