### ISSUE TITLE
Please provide an icon for weather.weatherbit that matches the current conditions. 

### ISSUE THREAD

**Issue by mniquette** [briis/weatherbit#26]

**Comment by briis** [comment]
Could you elaborate on this? Are you not seeing any icon for the Current Condition or is the icon you see not representing the actual condition?

**Comment by mniquette** [comment]
Thanks for your quick response. I use custom:multiple-entity-row a lot because it allows for a good looking content dense UI with progressive disclosure via more-info popups. I created a simple single-row weather control that combines the forecast and state from weatherbit with data from my PWS. The resulting control produces charts, etc. through more-info popups activated by clicking on its various weather data elements. It's great for phone displays. The main entity for this weather control is a template sensor that implements an active icon that matches the weatherbit state and I overrode the template sensor more-info with the weatherbit more-info for the detailed current/forecast information. Unfortunately custom:multiple-entity-row recently removed the ability to override the main entity more-info. So I'm stuck with either an active icon (template sensor) or the more-info current/forecast  popup (weatherbit). I believe that if the weatherbit entity provided an active icon in attributes, I could make weatherbit the main entity for my weather control and get both icon and more-info. Presently the weatherbit icon can be modified but it appears to be fixed, unless I'm missing something. Thanks for your consideration.

**Comment by briis** [comment]
Thanks for clarifying, now your question makes sense.
Just to make sure: You basically want the state of the *weather* entity, duplicated in an attribute? Is that correctly understood?
If this is what you want, try and look at the `alt_condition` attribute on the `weather` entity. I think this contains what you want?

**Comment by mniquette** [comment]
Actually no, I'm aware of the alt_condition. What I'm wondering is if weatherbit can add an icon attribute that changes with the state. Here is the code from my template sensor.

         icon_template: >
          {% set night = is_state('sun.sun', 'below_horizon') %}
          {% set w = states('weather.weatherbit') %}
          {% if w == 'unavailable' %} mdi:radar
          {% elif w == 'exceptional' %} mdi:weather-cloudy-alert
          {% elif w == 'partlycloudy' %}
            {% if night %} mdi:weather-night-partly-cloudy
            {% else %} mdi:weather-partly-cloudy {% endif %}
          {% elif w == 'clear-night' %} mdi:weather-night
          {% else %} mdi:weather-{{w}} {% endif %}

So the icon attribute would hold the text name of the appropriate icon to display as per other entities in HA.

**Comment by briis** [comment]
Normally if you add `mdi:weather-` in front of `alt_condition`, then you should get the correct icon. 

If that does not work, I have made a little change, so that there now is a new attribute called `mdi_icon` that contains the full icon name based on current condition. Could you test this for me, and let me know if this is what you want?

To install it go to the `custom_components\weatherbit` directory in this Github, and download the following two files:
`weather.py` and `const.py`

Copy the two files to the same directory in your Home Assistant installation, overwriting the previous ones. Then restart Home Assistant. When back up, you should now see the new attribute called `mdi_icon`.

**Comment by mniquette** [comment]
Sorry, that won't work. It's not that I want to determine the icon name (I can already do that as evidenced by the code above). 

When Lovelace displays a plain-old entity row, it shows an icon, a name, and a state. HA gets the name and icon from the entity's attribute list. Since the weatherbit entity currently doesn't specify an icon, a default static icon (cloud) is assigned by the system. You can change this default icon in the HA entity UI but it's still static.

However, if weatherbit had its own icon attribute (which is simply the text string of the icon file to use) it could provide an active icon that changes with the weather. As the icon changed, Lovelace would then automatically change the entity row display. This is similar to how battery level icons are displayed for battery entities,

I hope that explains it more clearly. Sorry for being a pain.

**Comment by briis** [comment]
FINALLY I understand what you want - sorry its taken so long.
Instead of the fix with the new attribute `mdi_icon` I am now assigning that value to the standard `icon` attribute. So the entity row should now display the correct icon.

Try and download the two files mentioned in my previous post, and see if that does not fix your problem.

**Comment by mniquette** [comment]
Okay finally tested this out and it works as far as I can tell. Unfortunately it's been cloudy here so I used the States tool to change the icon attribute, verified the entity row icon changed, and then waited for weatherbit to change it back to cloudy which all happened flawlessly. Thank you! Question what icon do you use if the service is unavailable? I was using mdi:radar.

**Comment by briis** [comment]
Glad it works.
I have set this icon `mdi:weather-cloudy-alert` when not found, as this is never used. I have no preference, would you prefer the radar icon?

**Comment by mniquette** [comment]
Yeah, it's working great.  It's raining now and the icon is correctly showing rain! I use the weather-cloudy-alert icon for weather alerts. I prefer the radar icon as it says to me it's looking for the service ( and it's kind of a weather symbol too).

**Comment by briis** [comment]
Perfect. I'll change it to radar and make the official release.

**Comment by briis** [comment]
Release 0.3.4 is out including this fix. I'll close it now.
