### ISSUE TITLE
Out-of-sync icons in forecast data

### ISSUE THREAD

**Issue by Landshark77** [briis/weatherbit#27]
Not sure when this started occurring, but there seems to be a problem with the icon and the weather_icon attributes being out of sync.  If you look at the two examples below, in the day 1 forecast, weather_icon is heavy rain, but icon is set to partly cloudy. Similar issue with the day 2 forecast: weather_icon is broken clouds, but icon is set to pouring.  Restart of HA corrects the issue, but I've never seen it fix itself.  Was thinking it would correct itself after the next API update, but that doesn't seem to be the case.  I have it set to update the forecast every 30min, with current data updating every 10min.  Running HA 2020.12.2 and WeatherBit integration v.0.34.1.

**sensor.weatherbit_forecast_day_1**
```
attribution: Powered by Weatherbit.io
datetime: '2021-01-06T00:00:00'
temperature: 63.9
templow: 48.4
precipitation: 0.69
snow: 0
cloudiness: 75
precip_prob: 95
wind_speed: 9.3
wind_bearing: 183
weather_text: Heavy rain
weather_icon: r03d
friendly_name: Weatherbit Forecast Day 1
icon: 'mdi:weather-partly-cloudy'
```

**sensor.weatherbit_forecast_day_2**
```
attribution: Powered by Weatherbit.io
datetime: '2021-01-07T00:00:00'
temperature: 49.8
templow: 41
precipitation: 0
snow: 0
cloudiness: 51
precip_prob: 0
wind_speed: 13.5
wind_bearing: 320
weather_text: Broken clouds
weather_icon: c03d
friendly_name: Weatherbit Forecast Day 2
icon: 'mdi:weather-pouring'
```

**After a restart of HA:**

```
> attribution: Powered by Weatherbit.io
> datetime: '2021-01-06T00:00:00'
> temperature: 63.9
> templow: 48.4
> precipitation: 0.69
> snow: 0
> cloudiness: 75
> precip_prob: 95
> wind_speed: 9.3
> wind_bearing: 183
> weather_text: Heavy rain
> weather_icon: r03d
> friendly_name: Weatherbit Forecast Day 1
> icon: 'mdi:weather-pouring'
```

```
> attribution: Powered by Weatherbit.io
> datetime: '2021-01-07T00:00:00'
> temperature: 49.8
> templow: 41
> precipitation: 0
> snow: 0
> cloudiness: 51
> precip_prob: 0
> wind_speed: 13.5
> wind_bearing: 320
> weather_text: Broken clouds
> weather_icon: c03d
> friendly_name: Weatherbit Forecast Day 2
> icon: 'mdi:weather-cloudy'
```

**Comment by briis** [comment]
This has been inactive for long, and I do believe all icons are correct. Else re-open.
