### ISSUE TITLE
not available in HACS Store

### ISSUE THREAD

**Issue by Pattern91** [briis/weatherbit#28]
I can't find it in HACS Store. Could you provide an example.yaml and show how to configure it in config.yaml?

**Comment by briis** [comment]
It is part of the default HACS store, and I can find it.
If you just installed HACS, then it needs some time to populate.

When you are on the HACS page, do a hard refresh of your browser and try again.

**Comment by Pattern91** [comment]
I just found it under: "Add repository"

**Comment by danielo515** [comment]
Yeah, I also had to go to "Add repository"
