### ISSUE TITLE
Where to configure?

### ISSUE THREAD

**Issue by danielo515** [briis/weatherbit#29]
Hello.
The documentation says that, after installing the integration you have to go to "configuration" and then integrations page. But it is not clear to me if you mean the configuration page of HACS store, or the main configuration of home assistant.
In none of those places I see anything to configure the weatherbit integration. This is what I see on my hassio integrations page:

![image](https://user-images.githubusercontent.com/2270425/106352213-5cdbbb80-62e1-11eb-88a1-55fcb31b52d3.png)

**Comment by briis** [comment]
Home Assistant comes with a lot of Integrations pre-installed, but for Integrations like Weatherbit, it is not part of the default HA. So therefore you can use HACS to get the needed files downloaded to the right location in HA. And that is the only thing HACS does. 
So once you installed the files via HACS, you will have to restart HA, for it to recognise the new Integration. Once HA is up again, you do as it says in the guide. Go to Settings and Integrations - then click the '+ ADD INTEGRATION' in the lower right corner. You can now search for Weatherbit.
Note: If it is not showing up, do a hard refresh of your browser when on the Integration Page - that clears the cache and you should be able to find Weatherbit.

**Comment by danielo515** [comment]
Sorry for not being clear. I have HACS and I have installed the extension with it.
Going to an incognito window (I don't like clearing my cache) the extension now appears on the integrations available to add.
Thank you very much. It is very annoying following all the steps and that home assistant decides to not work properly. Maybe it is possible to add this little advice you gave me to the readme?

**Comment by briis** [comment]
Glad it worked. I will write up something on the README. I will close this now.
