### ISSUE TITLE
Feature request pollen

### ISSUE THREAD

**Issue by barryhartman** [briis/weatherbit#31]
Hi,

Very nice project. Could it also support the pollen information from the weatherbit api (https://www.weatherbit.io/blog/post/api-update-april-2020-pollen-api-lunar-phase)?

Kind regards,
Barry

**Comment by briis** [comment]
I will look in to this as soon as I have time.

**Comment by briis** [comment]
I just did some digging in to this, and Airquality data is only available under the Advanced plan, which currently is 470$ pr month.
This Integration will only support what you get on the Free Tier plan. So I will not implement this. Sorry.

**Comment by barryhartman** [comment]
Ok, didn't know it cost money. Thanks for investigating.
