### ISSUE TITLE
please add system integration option 'enable polling for updates'

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#34]
as per discussion in https://community.home-assistant.io/t/weatherbit-io-current-weather-and-forecast-data/200224/266?u=mariusthvdb

please consider adding this:

<img width="584" alt="Schermafbeelding 2021-06-04 om 11 42 38" src="https://user-images.githubusercontent.com/33354141/120783827-b6702300-c52b-11eb-8a7c-8dff61f1542c.png">

to

<img width="494" alt="Schermafbeelding 2021-06-04 om 11 42 48" src="https://user-images.githubusercontent.com/33354141/120783844-bb34d700-c52b-11eb-887a-1553b6e331ea.png">

thanks!

**Comment by briis** [comment]
Sorry I did not visit this for a while. But this is not something I have to, as of 2021.6 it is already there as you can see from the picture below. Just click on the 3 Dots in the lower right corner, and then select *System Options*.
<img width="597" alt="Skærmbillede 2021-10-17 kl  15 54 46" src="https://user-images.githubusercontent.com/24776272/137630512-e1b0e933-1ed5-4347-9bd9-bb35e9e26319.png">

I will close this now.
