### ISSUE TITLE
Access to weather code

### ISSUE THREAD

**Issue by woz86** [briis/weatherbit#35]
Does this integration give access to the current weather code? I can see it in the Weatherbit API but I can't seem to get it in HASS. Am I missing something?

**Comment by briis** [comment]
I am not sure what you mean. Could you point me to what you believe you are missing from the API?

**Comment by woz86** [comment]
In the Weatherbit API, (https://www.weatherbit.io/api/weather-current) there is a field in the JSON called weather code.

**Comment by briis** [comment]
OK, got it. Yes the code is retieved, but not displayed as an integer value. Instead it is used to give the state of the weather entity, by translating this code in to a state used in Home Assistant. Does this answer your question?

**Comment by woz86** [comment]
Yes thanks. I can work with that. Thanks
