### ISSUE TITLE
Please Add Hourly Forecast

### ISSUE THREAD

**Issue by wiesel24** [briis/weatherbit#36]
Hi, thank you for your efforts with this integration. Everything Works fine and accurate. But it would be an enahncement if there would be also 1h forecast sensors available. Is this possible? Cause the weatherbit API documentation says it is possible up to 48h for non premium users.
Thx
regards
wiesel

**Comment by briis** [comment]
I will look at it as soon as I have time.

**Comment by wiesel24** [comment]
cool, thank you very much! Here is the link to the API documentation.
https://www.weatherbit.io/api/weather-forecast-120-hour

**Comment by briis** [comment]
Unfortunately Non-Premium users does not equal the Free plan. Which means that this is not available unless you have a paid plan. I admit the documentation is a bit confusing. But have a look at this site: https://www.weatherbit.io/pricing

Just to be sure I tested retrieving data with my Free API Key and I get this error: `{"error":"Your API key does not allow access to this endpoint."}`

So this will not be done, as I only support features that are in the Free Plan. Sorry.
