### ISSUE TITLE
sensor.weatherbit_weather_alerts doubles the alerts

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#37]
Not sure if this is new but in the midst of beta testing 2021.10, so having a closer look at most things...

  {{state_attr('sensor.weatherbit_weather_alerts','alerts')}} shows the sensor list the alerts twice
```
attribution: Powered by Weatherbit.io
alerts:
  - city_name: Roosendaal
    title: Wind
    description: >-
      Dutch(nl-NL): Aan zee kans op zware windstoten van 75-80 km/uur, met name
      bij buien. Kans op windstoten. Verkeer en buitenactiviteiten kunnen hinder
      ondervinden. Volg weerberichten en waarschuwingen.

      English(en-GB): At the coast risk severe gust of 70-80 km/hr, especially
      near showers. BE AWARE of  debris being blown around. Localised outdoor
      activity disruption is possible due to debris.
    severity: Advisory
    effective_local: '2021-10-05T22:00:00'
    expires_local: '2021-10-06T10:00:00'
    uri: https://meteoalarm.org?geocode=EMMA_ID:NL009
    regions:
      - Zuid-Holland,NL
  - city_name: Roosendaal
    title: Wind
    description: >-
      Dutch(nl-NL): Aan zee kans op zware windstoten van 75-80 km/uur, met name
      bij buien. Kans op windstoten. Verkeer en buitenactiviteiten kunnen hinder
      ondervinden. Volg weerberichten en waarschuwingen.

      English(en-GB): At the coast risk severe gust of 70-80 km/hr, especially
      near showers. BE AWARE of  debris being blown around. Localised outdoor
      activity disruption is possible due to debris.
    severity: Advisory
    effective_local: '2021-10-05T22:00:00'
    expires_local: '2021-10-06T10:00:00'
    uri: https://meteoalarm.org?geocode=EMMA_ID:NL009
    regions:
      - Zuid-Holland,NL
friendly_name: Weatherbit Weather Alerts
icon: mdi:alert
```

<img width="679" alt="Schermafbeelding 2021-10-05 om 14 12 47" src="https://user-images.githubusercontent.com/33354141/136020441-346b5e72-83ed-4669-a6c1-5a964a34bc77.png">
<img width="1149" alt="Schermafbeelding 2021-10-05 om 14 15 35" src="https://user-images.githubusercontent.com/33354141/136020453-047dc552-6bb8-4e89-9405-c2cbbb8b6c5c.png">

**Comment by briis** [comment]
I unfortunately do not get many alerts here in Denmark. There is nothing in the code that should add it twice. I will to find a location that has many alerts, and then I will check up on it.

**Comment by briis** [comment]
V1.0.0 released, implementing a new way of retrieving and displaying alerts. Please re-open if the issue occurs again.

**Comment by Mariusthvdb** [comment]
sorry to have to re-open this. the alert sensor even has 2 as state now ;-):

![20211225_085447000_iOS](https://user-images.githubusercontent.com/33354141/147388973-e6abb51a-a3e4-412a-961e-1800c968e6c9.png)

![20211225_085502000_iOS](https://user-images.githubusercontent.com/33354141/147388974-089dcdb1-b0bb-457c-8dc5-1f55b302941b.png)

**Comment by briis** [comment]
Yes and that is because the raw data has 2 alerts. I don't know why 2 alerts are posted by the Met office. If you look at the details they don't contain the exact same data. There are some differences. So I don't see this as a bug.
