### ISSUE TITLE
implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by JuhaFIN1** [briis/weatherbit#42]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 19:33:14 (30 occurrences)
Last logged: 19:33:15

Entity sensor.weatherbit_forecast_day_3 (<class 'custom_components.weatherbit.sensor.WeatherbitSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.weatherbit_forecast_day_4 (<class 'custom_components.weatherbit.sensor.WeatherbitSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.weatherbit_forecast_day_5 (<class 'custom_components.weatherbit.sensor.WeatherbitSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.weatherbit_forecast_day_6 (<class 'custom_components.weatherbit.sensor.WeatherbitSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.weatherbit_forecast_day_7 (<class 'custom_components.weatherbit.sensor.WeatherbitSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by briis** [comment]
Thank you for reporting this. I am aware of this, and I have a brand new version with many changes in the works, that are also fixing this.

This is the same issue as #41

**Comment by briis** [comment]
V1.0.0 released, fixing this issue.
