### ISSUE TITLE
alert (attributes) not ready?

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#45]
on the binary_sensor for the alert, some of the attributes aren't populated (anymore)

<img width="653" alt="Schermafbeelding 2021-12-23 om 08 50 21" src="https://user-images.githubusercontent.com/33354141/147207004-6f23b24d-f60d-48e2-9039-ad42c3cbb491.png">

dont think it is a user error, but maybe? Or is it the new integration not catching up with the data yet

please have a look? thanks!

**Comment by briis** [comment]
I just check the 0.34.4 source, and I have never delivered a binary sensor as part of this Integration. Are you sure this is not something you did as a Template sensor?

**Comment by briis** [comment]
The alert sensor has changed, so that if no alerts, the attributes are empty. I would check for the state of the alert sensor, if larger than 0, then read the attributes.

**Comment by Mariusthvdb** [comment]
yes! I had completely forgotten about my own template binary:
```
     - unique_id: weatherbit_alert
        name: Weatherbit Alert
        state: >
          {{states('sensor.weatherbit_weather_alerts')|int(default=0) > 0}}
        attributes:
          title: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
              {{state_attr('sensor.weatherbit_weather_alerts','alerts')[0].title}}
            {% else %} No alert
            {% endif %}
          region: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
            {{state_attr('sensor.weatherbit_weather_alerts','alerts')
                               [0].regions[0]}}
            {% else %} No alert
            {% endif %}
          city: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
            City:?{{state_attr('sensor.weatherbit_weather_alerts','alerts')
                               [0].city_name}}
            {% else %} No alert
            {% endif %}
          description: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
              {{(state_attr('sensor.weatherbit_weather_alerts','alerts')
                [0].description_english).split(': ')[1].split('English')[0]}}
            {% else %} No alert
            {% endif %}
#[0].description.split('nederlands:')[1].split('français')[0]
          severity: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
            {{state_attr('sensor.weatherbit_weather_alerts','alerts')[0].severity}}
            {% else %} No alert
            {% endif %}
          effective: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
            {{as_timestamp(state_attr('sensor.weatherbit_weather_alerts','alerts')
              [0].effective,none)|timestamp_custom('%H:%M %D',default='Not yet set')}}
            {% else %} No alert
            {% endif %}
          expires: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
            {{as_timestamp(state_attr('sensor.weatherbit_weather_alerts','alerts')
              [0].expires,none)|timestamp_custom('%H:%M %D',default='Not yet set')}}
            {% else %} No alert
            {% endif %}
          uri: >
            {% if states('sensor.weatherbit_weather_alerts')|int(default=0) > 0 %}
            {{state_attr('sensor.weatherbit_weather_alerts','alerts')
              [0].uri}}
            {% else %} No alert
            {% endif %}
        device_class: safety
        availability: >
          {{states('sensor.weatherbit_weather_alerts') not in ['unavailable','unknown']}}
```

fixed it and might need some polishing up...

thanks for reminding me

**Comment by briis** [comment]
If an alert occurs this is the code that adds attributes to the alert sensor:

```python
                data.append(
                    {
                        f"Alert No {count}": "-------------------",
                        ATTR_ALERT_TITLE: item.title,
                        ATTR_ALERT_SEVERITY: item.severity,
                        ATTR_ALERT_EFFECTIVE: item.effective_utc,
                        ATTR_ALERT_ONSET: item.onset_utc,
                        ATTR_ALERT_ENDS: item.ends_utc,
                        ATTR_ALERT_EXPIRES: item.expires_utc,
                        ATTR_ALERT_URI: item.uri,
                        ATTR_ALERT_REGIONS: item.regions,
                        ATTR_ALERT_DESCRIPTION_EN: item.en_description,
                        ATTR_ALERT_DESCRIPTION_LOC: item.loc_description,
                    }
                )
````
Where the attribute names are specified as such:

```python
ATTR_ALERTS = "alerts"
ATTR_ALERT_DESCRIPTION_EN = "description_english"
ATTR_ALERT_DESCRIPTION_LOC = "description_local"
ATTR_ALERT_EFFECTIVE = "effective"
ATTR_ALERT_ENDS = "ends"
ATTR_ALERT_EXPIRES = "expires"
ATTR_ALERT_ONSET = "onset"
ATTR_ALERT_REGIONS = "regions"
ATTR_ALERT_SEVERITY = "severity"
ATTR_ALERT_TITLE = "title"
ATTR_ALERT_URI = "uri"
`````

**Comment by Mariusthvdb** [comment]
well, the description field is a bit odd:

<img width="1447" alt="Schermafbeelding 2021-12-23 om 09 33 15" src="https://user-images.githubusercontent.com/33354141/147212156-6e0ae702-8c48-44c8-851d-2ffc811906e3.png">

description_local results in English(en-GB), where .description_english contains my local Dutch(nl-NL), which I have to filter out:

```
{{(state_attr('sensor.weatherbit_weather_alerts','alerts')
    [0])}}


{{(state_attr('sensor.weatherbit_weather_alerts','alerts')
    [0].description_english).split(': ')[1].split('English')[0]}}


{{(state_attr('sensor.weatherbit_weather_alerts','alerts')
                [0].description_local)}}
```

**Comment by briis** [comment]
Yes I can see that. This is a hard thing to actually code, as they don't turn up that often. I was trying to do a *Scraper* in the IO module to separate english from local language, and it worked in the test data I got from a station in Italy, but the format for you is obviously different. Could you give me a Latitude/Longitude position that will give me the data you see? Then I can look at the raw data and see if something can be done about it.

**Comment by Mariusthvdb** [comment]
also, the city field is no longer there, and changed to region. At least, in the data I can see from the base sensor? which is too bad really, cant imagine they dont support that any longer?

living in Roosendaal (which is what I saw I the sensor before)
51.53212672512803, 4.4592306226337755  obviously not me so no need to be hidden ;-)

btw, is it correct we are seeing meteoalarm (https://meteoalarm.org/?geocode=EMMA_ID%3ANL009) as attribution and not weatherbit.io? even though my zone_id is listed in the integration setup Location ID: D8604, this does not get returned in any attribute, or elsewhere for that matter?

**Comment by briis** [comment]
Below is the raw data returned from the alerts section. As this is now returned together with the current observations, the city name is still there, I just forgot to include it in the alerts, but will correct that.

> btw, is it correct we are seeing meteoalarm (https://meteoalarm.org/?geocode=EMMA_ID%3ANL009) as attribution and not weatherbit.io?

Yes, that is correct. This is where Weatherbit seems to get the alerts from. I just checked the previous way of retrieving alerts, and this returns exactly the same data. I don't know if that is a change from before, as the Danish Met Institute is not good at posting weather alerts, so I never see any alerts.

> even though my zone_id is listed in the integration setup Location ID: D8604, this does not get returned in any attribute, or elsewhere for that matter?

Not sure what you mean here, why is that an issue? I don't use the Location ID for anything.

**Raw Alert Data**
```json
{
    "regions": ["Zuid-Holland,NL"],
    "ends_utc": "2021-12-23T11: 00: 00",
    "effective_local": "2021-12-23T09: 00: 00",
    "onset_utc": "2021-12-23T08: 00: 00",
    "expires_local": "2021-12-23T12: 00: 00",
    "expires_utc": "2021-12-23T11: 00: 00",
    "ends_local": "2021-12-23T12: 00: 00",
    "uri": "https://meteoalarm.org?geocode=EMMA_ID:NL009",
    "onset_local": "2021-12-23T09:00:00",
    "effective_utc": "2021-12-23T08:00:00",
    "severity": "Advisory",
    "title": "Snow/Ice",
    "description": "Dutch(nl-NL): Kans op gladheid door regen op bevroren ondergrond, IJzel. Kans op gladheid. Alle verkeersdeelnemers kunnen hinder ondervinden. Pas uw rijgedrag aan. Volg weerberichten en waarschuwingen.\nEnglish(en-GB): Risk of slippery roads due to rain on frozen roads, freezing rain.G. BE AWARE of widespread snow and/or ice on roads and pavements. Localized disruption of outdoor activities.  Take care when walking, cycling or driving due to slippery surfaces."
}
````

**Comment by Mariusthvdb** [comment]
thanks, and great you will restore the city

not an issue about the location ID, I just figured it might have to do with the city_name not being returned...

what I still dont get is the description, and how it is returned in the integration sensors. As Ive shown above, I have to create a complex jinja template to make that appear.

How do you get that raw alert data set? if I use the direct api call via https://api.weatherbit.io/v2.0/current (and then my data in that url), I dont get any Alert at all, only all other data for the location

**Comment by briis** [comment]
I have now found a smarter way to split the local and english text. So you will have an attribute called `description_english` that holds the english text and one called `description_local` that holds the text in local language. So you should be able just to pull that attribute. 
Remember alert attributes are passed as an array of alerts, so you will either have to loop through them or select the specific index like: `sensor.weatherbit_weather_alerts[0]` (Not sure if that is the right way to do in Jinja)

> How do you get that raw alert data set? if I use the direct api call via https://api.weatherbit.io/v2.0/current 

There is a not very well documented parameter you can add to the url called `include=alerts`, if you add that to the above, then alerts are returned together with the current data.

**Comment by Mariusthvdb** [comment]
thanks! works like a beauty ;-)

odd thing: if I enter my city_name=Roosendaal, it returns the data for Rozendaal, which is also a city in NL, but nowhere near.... yet, if I enter my postal coded as parameter it works fine, and, lo and behold, even shows my city_name correctly 


<strike>wondering if I could make a rest sensor with that api endpoint?</strike> 
```
rest:

  - resource: !secret weatherio_api_url
    scan_interval: 86400
    method: GET
    sensor:
      - name: Weatherbit local data
        value_template: >
          {{value_json.count}}
        json_attributes:
          - data
          - alerts
```

**Comment by briis** [comment]
Have a look here: https://www.weatherbit.io/api/meta 
This is what Weatherbit uses as sources - and there is a big difference in data reported and update frequencies.

**Comment by Mariusthvdb** [comment]
I will have a look there, thanks.

my rest sensor though sees the same issue with the alert, is all in there, in 1 big list:
<img width="1446" alt="Schermafbeelding 2021-12-23 om 11 44 13" src="https://user-images.githubusercontent.com/33354141/147229321-9a285c9f-ba00-4563-90e5-bdaa4eace006.png">

easy enough to template to
```
{{state_attr('sensor.weatherbit_local_data','alerts')[0].description.split('English(en-GB)')[0]}}
```
or even 
```
{{state_attr('sensor.weatherbit_local_data','alerts')[0].description.split('English(en-GB)')[0].split('Dutch(nl-NL): ')[1]}}
```

but it remains unfortunate is isnt split from the data source already

**Comment by Mariusthvdb** [comment]
anyways, I can safely lose this issue, as it was a user error ;-)
thanks for your ongoing efforts!
