### ISSUE TITLE
Updated timestamp missing?

### ISSUE THREAD

**Issue by ffeingol** [briis/weatherbit#49]
Prior to the 1.x upgrade there was a timestamp when the data was retrieved from weatherbit.  It it possible to get that back?

**Comment by briis** [comment]
Sure thing. I will create a sensor called `observation_time` that will hold the date and time when the data was recorded. Depending on the station location, observations might occur anything from every 30 minutes to once a day.

You can see update frequencies on this webpage: https://www.weatherbit.io/api/meta

**Comment by briis** [comment]
Just released 1.0.3, which fixes this.
