### ISSUE TITLE
v1.0.3 - Incorrect Temperature on Weather Cards

### ISSUE THREAD

**Issue by dbrigner** [briis/weatherbit#50]
The WeatherBit / HA integration is incorrectly reporting the current temperature on weather cards.  The temperature reported on the actual **_sensor.weatherbit_air_temperature_** sensor is correct.

For example, my Weatherbit Air Temperature sensor is currently (and correctly) reporting 75.4F.  The temperature on the weather card is showing 69F.  The custom and stock weather cards are both reflecting the same, incorrect temperature.

**Comment by briis** [comment]
They are technically not wrong. The data you see in the Weather Card are the ones that come with the Forecast data, and as they are not updated with the same frequency as the current data, they will be different.
But I have now switched the Weather Entity to use the same data as the sensors, where this is relevant and possible, so with the next release they should be in sync.

**Comment by briis** [comment]
Released V1.0.4 where this is fixed.

**Comment by dbrigner** [comment]
Thank you, Briis for the quick response!  However, while the weather card temperature issue seems to be resolved, the barometric pressure and visibility values do not seem to be correctly reporting on the weather cards.  For example, _**Weatherbit Sea Level Pressure**_ reads 29.74 inHg on the sensor, but 0.43 on the weather cards.   _**Weatherbit Visibility**_ sensor is 3.1mi, with the weather card showing it as 0.44mi.  Everything else on the weather card seems to be in line with what the sensors are reporting, as far as I can tell.

**Comment by briis** [comment]
Yes I can see this. The weather entity unfortunately has changed the default units for some of the metrics in current values, so that pressure should now be reported in psi and not inHg. I decided now that the value is more important that the unit specified, so the values you will see now should be what you expect, but just note that when you click on a weather card, you will see pressure reported as psi but the value is inHg.

**Comment by briis** [comment]
V1.0.5 is now out, hopefully this fixes the value issues.
