### ISSUE TITLE
Warning found in logs 

### ISSUE THREAD

**Issue by tedrudie** [briis/weatherbit#51]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:543
First occurred: 8:05:50 PM (1 occurrences)
Last logged: 8:05:50 PM

Updating state for sensor.weatherbit_temperature (<class 'custom_components.weatherbit.sensor.WeatherbitSensor'>) took 1.458 seconds. Please report it to the custom component author.

**Comment by briis** [comment]
Thanks for reporting this. There is not much I can do about it - sometimes Weatherbit is slow in delivering the data, and I pull as little as possible.
