### ISSUE TITLE
Double entities from time to time after HA restart

### ISSUE THREAD

**Issue by ge8020** [briis/weatherbit#52]
Hello!
I was not able to reproduce the exact conditions needed for this to happen, but sometimes on a HA restart i have all weatherbit entities twice and all copies have "_2" as suffix.
In that case, the integration leaves the original ones (without suffix)  orphaned (with the ! sign) and not useable.
I have to delete the whole integration and install it again to make them go away and have the correct values from the entities again on my cards.
Afterwards it goes well for a few restarts but randomly this happens again.
Am i the only one with this strange behavior?

**Comment by Landshark77** [comment]
Noticed this problem as well.  Happened after the update to 2021.12.8.  I've restarted HA many times before the update to 2021.12.8 and have not seen this problem.  Not sure what triggered it this time.

**Comment by briis** [comment]
This has not been reported before, so currently you are the only one. The only scenario I see this might happen, is if the latitude and longitude you supply, can fetch more than one station nearby, and then once in awhile, it pulls the data from the other station than the one currently setup.

How many decimals do you have behind the latitude and longitude? If not that many, maybe try and put more decimals on, to ensure it always picks the same station. Eventually I might need to rewrite some stuff, but I am not going to do that before I know what is causing the error.

Did you check the Home Assistant Log? Anything in there?

If you look at *WeatherBit* on the Integrations page. When you see two entities popping up, are there two entities defined here? If yes, could you click on each one, and then click on devices, there should now be a list with a column called *Model* - are they the same for both entities?

**Comment by Landshark77** [comment]
For me, I only have one device defined under the integration with 64 entities.  Only the ones that end with a "_2" are working.  No signs of errors in the HA logs.  Only saw this - "[homeassistant.helpers.entity_registry] Registered new weather.weatherbit entity: weather.weatherbit_2".  



![Screenshot from 2022-01-05 07-21-46](https://user-images.githubusercontent.com/27645488/148224474-760e0529-44b1-4892-91f7-00fd0578b000.png)


![Screenshot from 2022-01-05 07-18-35](https://user-images.githubusercontent.com/27645488/148224067-6e4bf991-9183-44e3-825c-9a88294f40e6.png)

**Comment by briis** [comment]
Ok, thanks. I need to dig in to why this can happen.

**Comment by briis** [comment]
I have just released V1.0.6, which I do believe will fix this (If my theory is correct). Unfortunately this WILL create all the entities again, as the Unique ID changes, but hopefully this is the last time.
Closing the issue, but if it does not fix your problem, please re-open.
