### ISSUE TITLE
humidity very precise

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#53]
<img width="325" alt="Schermafbeelding 2022-01-05 om 17 16 40" src="https://user-images.githubusercontent.com/33354141/148251351-92b57837-2c67-4b8a-a941-6e61355f98ef.png">

seems a bit to much ;-) personally, I wouldn't need decimals here at all, but if must, 1 would suffice?

using todays release 1.0.6

works beautifully as ever, so thanks for that!

**Comment by briis** [comment]
You are right, I missed that. Will fix in the next release. 
And thanks 🙏

**Comment by Mariusthvdb** [comment]
😊

**Comment by briis** [comment]
Will be in V1.0.7 when that is released. Closing now.
