### ISSUE TITLE
Observation time is in UTC

### ISSUE THREAD

**Issue by lymanepp** [briis/weatherbit#60]
Observation time is in UTC. Normally that would be fine, but Lovelace displays that as an offset from the current local time instead of displaying the actual time.

![image](https://user-images.githubusercontent.com/4195527/151253798-d425eceb-6fd2-4c8b-b01e-cc9011a6984a.png)

**Comment by briis** [comment]
I now removed the DEVICE_CLASS TIMESTAMP from the sensor, and converted the time to Local time.
Could you download `sensor.py` from this Github and replace the same file in `custom_components/weatherbit` and then restart HA, to see if that fixes your issue?

**Comment by briis** [comment]
And just to make sure you know - This DateTime tells when WEATHERBIT has last updated the data for that location, not the last time this Integration has pulled data from WeatherBit. Som locations only update once a day.

**Comment by lymanepp** [comment]
Your commit changed the display format, but the time was still off by the UTC offset.

![image](https://user-images.githubusercontent.com/4195527/151595888-f00a4765-deb2-41b9-b943-ad1ba904c155.png)

I submitted a PR for py-weatherbit to fix the root cause. With that fix, you can probably revert the changes in https://github.com/briis/weatherbit/commit/05903401fb0c6abfd238c98593331c1ab402e24c

**Comment by briis** [comment]
Released 1.0.8, where this is fixed. Please check and close if you agree.

**Comment by lymanepp** [comment]
The time is correct now! But I'd still prefer to see the observation time as a timestamp instead of a string (i.e., revert changes in https://github.com/briis/weatherbit/commit/05903401fb0c6abfd238c98593331c1ab402e24c).

**Comment by briis** [comment]
OK, I will revert it to a Timestamp. Try an download the `sensor.py` file, and overwrite as before. Then give the final go that this still shows the correct time.

**Comment by lymanepp** [comment]
Thanks Bjarne! It looks good to me.

![image](https://user-images.githubusercontent.com/4195527/151705880-9b87388a-ea60-452f-81fb-8c03e3170c98.png)

**Comment by briis** [comment]
Wonderful. Just keep the file you downloaded and that will then be in the next release.
