### ISSUE TITLE
Forecast day headers are a day behind

### ISSUE THREAD

**Issue by greg520820** [briis/weatherbit#62]
Edit:  Changed version number from 1.04 to 1.05.  Version 1.05 has the forecast and day synced, but all versions after 1.05 the forecast day header is off by one day.
 
All version after 1.05 the forecast is one day behind, at least for my time zone.  

On version 1.05 the entities created for sensor.weatherbit_forecast_day_1 is  datetime: '2022-02-23T16:00:00+00:00', but all version after 1.05 the entity is created with a datetime: '2022-02-23T**00**:00:00+00:00'.  I'm in the New York time zone, so the 00 hours minus 5 hours for the time zone correction makes the day 1 forecast header being marked as yesterday.

**Comment by briis** [comment]
I will look in to this. I am just moving house, so everything is packed down. Expect it to be a two weeks before I am back up.

**Comment by greg520820** [comment]
No rush. I'm running version 1.04 and it is working fine, but would like to get on the latest version. 

Good luck with the move.

**Comment by briis** [comment]
I have now made a pre-release of [1.0.9-beta.1](https://github.com/briis/weatherbit/releases/tag/v1.0.9-beta.1) which contains a potential fix. I need you all to test it out. If you run through HACS, you need Beta releases enabled to see it.
Looking forward to hear if this fixes it.

**Comment by greg520820** [comment]
Yes, the 1.0.9 beta works for me. The forecast days are correct. The sensor.weatherbit_forecast_day_1 and weather.weatherbit entities are both showing date/time stamp of 2022-04-17T16:00:00+00:00.

Thanks for fixing this issue.

**Comment by briis** [comment]
Sounds good. I will let it you run it for at least 24 hours, before making this official. Just to make sure it works.

**Comment by briis** [comment]
I have now released 1.0.9 - no changes from the previous beta, just making it official. Closing the issue.

**Comment by MichaelStruck** [comment]
I can verify this fixed the issue for me as well
