### ISSUE TITLE
Unable to install package pyweatherbitdata==1.0.13: 

### ISSUE THREAD

**Issue by B-Kramer** [briis/weatherbit#66]
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 7:40:11 PM (3 occurrences)
Last logged: 7:40:18 PM

Unable to install package pyweatherbitdata==1.0.13: ERROR: Could not find a version that satisfies the requirement pyweatherbitdata==1.0.13 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12) ERROR: No matching distribution found for pyweatherbitdata==1.0.13 WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

Just started getting this on a restart, on Home Assistant Core 2022.5.3.  It was working great before the HA update, and nothing else has changed.  I can see 1.0.13 on github, so not sure if something changed on pypi.

Kinda weird.

**Comment by briis** [comment]
I just did a new installation and I am not getting this error. It install `pyweatherbitdata ` version 1.0.13 fine.
I am not sure what the problem can be, but it does not seem to be with the integration.

**Comment by B-Kramer** [comment]
The problem actually stopped, not sure what it was but you can close.
Thanks.
