### ISSUE TITLE
deprecated `async_get_registry`

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#67]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: May 19, 2022, 10:47:18 (4 occurrences)
Last logged: May 19, 2022, 10:48:20

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for weatherbit using this method at custom_components/weatherbit/__init__.py, line 171: device_registry = await dr.async_get_registry(hass)

new warnings in the log ;-) 2022.6 dev etc

letting you know this is about to happen, please have a look?

**Comment by briis** [comment]
Perfect. Thanks @Mariusthvdb I will look in to this and make a fix ready for 2022.6

**Comment by briis** [comment]
Closing with release V1.0.10
