### ISSUE TITLE
Customizable polling interval?

### ISSUE THREAD

**Issue by clarsonJWU** [briis/weatherbit#7]
Would it be possible to customize the polling interval? I'd like to update the data more often than every 15 minutes. I understand part of it is to make sure we don't hit the daily api limit, especially if you use multiple locations, but if we only use 1 location, updating more frequently would be nice.

I use current cloud coverage in some of my automations and having more up to date data is necessary for it to work properly.

**Comment by briis** [comment]
Sure, it is possible. With this latest release, I can now set different intervals on Forecast and Current data, and I assume it is Current data were you would like to set a different update frequency?

**Comment by clarsonJWU** [comment]
Yes, current data is all that I would want to update more frequently.

**Comment by briis** [comment]
I will work on it. Stay tuned...

**Comment by briis** [comment]
I have now released 0.10 which implements polling intervals. If you are happy with the solution, please close this issue.
/B

**Comment by austwhite** [comment]
I've tested this and this all works.   I think the OP may have forgotten to close it.

@clarsonJWU are you happy with the new functions. :)

**Comment by clarsonJWU** [comment]
I was finally able to install and test the update and it is working as expected. Thank you so much for the quick turnaround!
