### ISSUE TITLE
cannot import name 'ATTR_FORECAST_NATIVE_PRECIPITATION

### ISSUE THREAD

**Issue by tottka** [briis/weatherbit#71]
Just updated to v1.0.11 and receiving the following in the log
Logger: homeassistant.setup
Source: setup.py:298
First occurred: 9:07:05 AM (2 occurrences)
Last logged: 9:07:05 AM

Unable to prepare setup for platform weatherbit.sensor: Platform not found (cannot import name 'ATTR_FORECAST_NATIVE_PRECIPITATION' from 'homeassistant.components.weather' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/weather/__init__.py)).

**Comment by briis** [comment]
Sorry, this got released too early, HA is not ready yet. 
Just for my records: What version of HA are you running?
Please downgrade to 1.0.10 and you should be running again.

**Comment by tottka** [comment]
Thanks for quick reply, downgraded and all is good.  I'm running HA 2022.6.7
