### ISSUE TITLE
Home Assistant Core

### ISSUE THREAD

**Issue by michael7835** [briis/weatherbit#74]
Integration not working with latest update.

**Comment by briis** [comment]
Please supply some debug logs

**Comment by michael7835** [comment]
It's back up but i'm still getting "integration not ready yet" "error
requesting data from Weatherbit:429" with a very long url. By the way,
thanks for all you do!

**Comment by briis** [comment]
The 429 error is because you are over the limit of 500 requests per day. If you go to the Integration you can adjust the update frequency. Try setting the Interval to 10 min instead of 5. It might take a day before your limit at WeatherBit is reset.

**Comment by michael7835** [comment]
Works great, thanks!

**Comment by briis** [comment]
👍🏻
