### ISSUE TITLE
running 2022.10.0 but this requires 2022.10

### ISSUE THREAD

**Issue by Mariusthvdb** [briis/weatherbit#77]
We get no HACS notification, and apparently can not install manually either because of this?

<img width="590" alt="Schermafbeelding 2022-10-06 om 09 22 49" src="https://user-images.githubusercontent.com/33354141/194243257-b1fd0d41-bd04-41dd-803c-272dd138d97d.png">

**Comment by briis** [comment]
Ups. I will fix this when I get to a Computer.

**Comment by briis** [comment]
Done now. Could please try again, and let me know how this goes.

**Comment by Mariusthvdb** [comment]
really odd, nothing happening. I reloaded HACS. No notification. I restarted HA. No notification. When I click Update Information, nothing happens. Click Redownload: shows the above warning...
Clicking Update give me the swirl, but nothing else I am afraid.

**Comment by briis** [comment]
Just tried it myself. Must be some sort of caching mechanism in HACS, that keeps overwriting the info in `hacs.json` on Github. I tried to modify the file `hacs.repositories` in the .storage area manually, but as soon as I click *Redownload* the 2022.10.0 gets overwritten with 2022.10.

I have not made any changes to the naming of my sensors, so I will try and remove the repository from HACS and the redownload it and see if this works.

**Comment by Mariusthvdb** [comment]
could it have to do with the new version() options in HA?
https://github.com/home-assistant/core/pull/78525
https://github.com/home-assistant/core/pull/78484

**Comment by briis** [comment]
Ok I got it now. Hacs actually gets the version number from within the release and not by reading the hacs.json file in the main repository. So I now made a new version 1.0.13 which just installed fine here on my site. So please try again.

**Comment by Mariusthvdb** [comment]
guess that did it:

<img width="693" alt="Schermafbeelding 2022-10-06 om 14 59 56" src="https://user-images.githubusercontent.com/33354141/194319158-4d00d452-2e05-43d3-8986-1d73ec4fd702.png">

yeah. thank you Bjarne. Will close!
