### ISSUE TITLE
More deprecation warnings

### ISSUE THREAD

**Issue by FamousL** [briis/weatherbit#79]
In addition to what the other warning that was previously posted also getting these:

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for weatherbit using this method at custom_components/weatherbit/__init__.py, line 160: device_registry = await dr.async_get_registry(hass)

Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for weatherbit using this method at custom_components/weatherbit/sensor.py, line 250: convert_pressure(value, PRESSURE_HPA, PRESSURE_INHG), 2

Detected integration that uses distance utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.DistanceConverter instead. Please report issue to the custom integration author for weatherbit using this method at custom_components/weatherbit/sensor.py, line 265: float(convert_distance(value, LENGTH_KILOMETERS, LENGTH_MILES))

custom_components.weatherbit.weather::WeatherbitWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

This is extending #78 

Editlist:
Added another warning, and noting extension from other issue.

**Comment by briis** [comment]
Can you tell me what version the Integration you are running, as everything you report has been fixed and released, except what you see in #78. (And this is done, just not released)

**Comment by FamousL** [comment]
My apologies, it seems hacs forgot I even had it installed so didn't update as it should have. Sorry for having you work through that.

**Comment by briis** [comment]
No problem. #78 will be released in a day two. Just waiting to see if anything else shows up.
