### ISSUE TITLE
Too many requests after upgrade.

### ISSUE THREAD

**Issue by michael7835** [briis/weatherbit#80]
Logger: homeassistant.config_entries
Source: config_entries.py:1088
First occurred: 1:09:40 PM (2 occurrences)
Last logged: 1:11:54 PM

Config entry 'Crooks Corner' for weatherbit integration not ready yet: Error requesting data from WeatherBit: 429, message='Too Many Requests', url=URL('https://api.weatherbit.io/v2.0/current?lat=42.0168750229593&lon=-71.49481236934663&key=d8b74d061ba44c4695adf1e54ba20c0e&lang=en&units=M'); Retrying in background

Tried adjusting, no luck.

**Comment by briis** [comment]
Same as #73. Please see answer.
