### ISSUE TITLE
Error since updating to HA 2022.11.0b0

### ISSUE THREAD

**Issue by gieljnssns** [briis/weatherbit#81]
```
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 09:14:19 (1 occurrences)
Last logged: 09:14:19

Unable to prepare setup for platform weatherbit.sensor: Platform not found (cannot import name 'LENGTH_MILLIMETERS' from 'homeassistant.util.unit_conversion' (/usr/src/homeassistant/homeassistant/util/unit_conversion.py)).
```

**Comment by briis** [comment]
Thanks for reporting. Fix is implemented, awaiting 2022.11 release

**Comment by gieljnssns** [comment]
Can you release a beta version?
Weatherbit isn't loading at all. So I can't test the ha beta.

**Comment by briis** [comment]
Will do when I get home from Work in a few hours

**Comment by briis** [comment]
Just released a beta, but done it while attending a meeting, so hopefully it works

**Comment by gieljnssns** [comment]
Updated again. 
no problem anymore.

**Comment by briis** [comment]
1.0.16 released which closes this issue.
