### ISSUE TITLE
Weatherbit integration has incorrect slider update values

### ISSUE THREAD

**Issue by Spirituss** [briis/weatherbit#90]
Weatherbit integration doesn't allow to set update periods lower than 60 mins with UI sliders, while default values are 5/30 mins. See the screenshots:

![Снимок экрана 2023-05-02 в 16 11 19](https://user-images.githubusercontent.com/47206760/235678491-e1b0f3ac-1637-4342-89af-ef2db643a210.png)
![Снимок экрана 2023-05-02 в 16 11 23](https://user-images.githubusercontent.com/47206760/235678496-c29c22c8-2c7c-4dff-a8a3-6ee1e9c567b7.png)

**Comment by greg520820** [comment]
About a year ago Weatherbit API reduced the number of calls allowed from 500 down to 50.  The default values shown are not usable, but the text could be updated to reflect the new  defaults of 60 min.

**Comment by Spirituss** [comment]
> The default values shown are not usable, but the text could be updated to reflect the new defaults of 60 min.

It's a good solution, looking forward.

**Comment by briis** [comment]
As @greg520820 wrote, we had to adjust the default and minimum values due to a change in the Free Tier plan at Weatherbit. Texts have now been updated to reflect that change. Will be in the next release
