### ISSUE TITLE
Weather is using a forecast attribute on an instance of WeatherEntity, this is deprecated

### ISSUE THREAD

**Issue by gieljnssns** [briis/weatherbit#91]
An error on the latest HA beta 2023.9.0b0
```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:339
Integration: Weather (documentation, issues)
First occurred: 00:51:57 (1 occurrences)
Last logged: 00:51:57

custom_components.weatherbit.weather::None is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author.
```

**Comment by briis** [comment]
I am aware of that. Hopefully I have a fix done before january 2024

**Comment by FamousL** [comment]
Hello, checking in on this, the integration is throwing some fun errors loading on 2024.1.

**Comment by nepozs** [comment]
Perhaps a monetary donation from users for at least a month of paid subscription would be helpful?

**Comment by briis** [comment]
> Perhaps a monetary donation from users for at least a month of paid subscription would be helpful?

Thanks for the offer, but I will not continue working on this. Simply to hard to work on with the few daily tests I can do, before my account is locked out. Again, this is open source, so anyone can fork it and continue the work. 😀
