### ISSUE TITLE
Frequent restarts of HA uses up call limit

### ISSUE THREAD

**Issue by magicus** [briis/weatherbit#92]
I have been modifying my HA config a lot today, trying different options, and restarting HA multiple times. After a while, the WeatherBit integration starting to signal an error. Some digging in the logs gave me that I have passed my limit of free calls.

I assume that the WeatherBit integration does a lookup at HA startup, regardless of how recent the last lookup was.

I suggest that the last returned data is cached, along with a timestamp, and at startup time, the timestamp is compared to the current time. If it is less than the selected call intervall, no call should be made.

**Comment by briis** [comment]
Yes this is how it is setup. Upon restart all integrations are relaoded.
After Weatherbit lowered the API limits so much as they did I lost interest in their API, and I will not make anymore changes to this. Eventually it will stop working with HA 2024.3 as the Forecast format has changed.

I have just not come around to making an End-Of-Life announcement.

**Comment by magicus** [comment]
I see. Do you know of any other free service which publishes cloud coverage numbers? (That is what I'm using it for)

Or otherwise, do you have some pointer on the 2024.3 forecast changes? (I might try to pick up the baton in keeping this alive)

**Comment by briis** [comment]
Again, I am sorry I have to leave you in the dark, but Weatherbit is not very friendly with us unless you want to pay. I found another Weather Provider that gives a Free Tier with a lot more calls, and I wrote an integration for that. They are called Visual Crossing and a link to the Integration is here: https://github.com/briis/visualcrossing

This has cloud coverage integrated.

**Comment by magicus** [comment]
Thanks!
